image: valensas/graalvm-static-image:java21.0.0

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - verify
  - publish

lint:
  stage: verify
  cache:
    paths:
      - .gradle
  variables:
    KUBERNETES_CPU_REQUEST: "1"
    KUBERNETES_CPU_LIMIT: "1"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "2Gi"
  script: ./gradlew lintKotlin

# This steps mysteriously fails. Disabled until a solution is found.
#test:
#  stage: verify
#  cache:
#    paths:
#      - .gradle
#  services:
#    - bitnami/postgresql:15.2.0
#  variables:
#    KUBERNETES_CPU_REQUEST: "2"
#    KUBERNETES_CPU_LIMIT: "2"
#    KUBERNETES_MEMORY_REQUEST: "8Gi"
#    KUBERNETES_MEMORY_LIMIT: "8Gi"
#    POSTGRES_DB: "r2dbc_test"
#    POSTGRES_USER: "db_user"
#    POSTGRES_PASSWORD: "db_pass"
#  script: ./gradlew nativeTest

publish:
  stage: publish
  cache:
    paths:
      - .gradle
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - |
      if grep -Eq "version\s+=\s+\"${CI_COMMIT_TAG}\"" ./build.gradle.kts
       then
         echo "Publishing ${CI_COMMIT_TAG} version"
         ./gradlew publish
       else
         echo "version '${CI_COMMIT_TAG}' must exist in the build.gradle.kts file."
         exit 1
       fi
